const getDesignationByPostTypes = {
    GET_DESIGNATION_BY_POST: '@@GET_DESIGNATION_BY_POST',
    GET_DESIGNATION_BY_POST_LOADING: '@@GET_DESIGNATION_BY_POST/LOADING',
    GET_DESIGNATION_BY_POST_SUCCESS: '@@GET_DESIGNATION_BY_POST/SUCESS',
    GET_DESIGNATION_BY_POST_ERROR: '@@GET_DESIGNATION_BY_POST/ERROR',

    // get zone type 
    GET_ZONE : "@@GET_ZONE",
    GET_ZONE_LOADING : "@@GET_ZONE/LOADING",
    GET_ZONE_SUCCESS : "@@GET_ZONE/SUCESS",
    GET_ZONE_ERROR : "@@GET_ZONE/ERROR",

}
export default getDesignationByPostTypes;