const GraphTypes = {
    GET_ANNUAL_SALARY_SUMMARY: '@@GET_ANNUAL_SALARY_SUMMARY',
    GET_ANNUAL_SALARY_SUMMARY_SUCCESS: '@@GET_ANNUAL_SALARY_SUMMARY_SUCCESS',
    GET_ANNUAL_SALARY_SUMMARY_LOADING: '@@GET_ANNUAL_SALARY_SUMMARY_LOADING',
    GET_ANNUAL_SALARY_SUMMARY_RESET: '@@GET_ANNUAL_SALARY_SUMMARY_RESET',
    GET_ANNUAL_SALARY_SUMMARY_ERROR: '@@GET_ANNUAL_SALARY_SUMMARY_ERROR',

    // sale vs salary types
    GET_SALES_VS_SALARY: '@@GET_SALES_VS_SALARY',
    GET_SALES_VS_SALARY_SUCCESS: '@@GET_SALES_VS_SALARY_SUCCESS',
    GET_SALES_VS_SALARY_LOADING: '@@GET_SALES_VS_SALARY_LOADING',
    GET_SALES_VS_SALARY_RESET: '@@GET_SALES_VS_SALARY_RESET',
    GET_SALES_VS_SALARY_ERROR: '@@GET_SALES_VS_SALARY_ERROR',

    GET_ANNUAL_TARGET_SUMMARY:"@@GET_ANNUAL_TARGET_SUMMARY",
    GET_ANNUAL_TARGET_SUMMARY_LOADING:"@@GET_ANNUAL_TARGET_SUMMARY_LOADING",
    GET_ANNUAL_TARGET_SUMMARY_SUCCESS:"@@GET_ANNUAL_TARGET_SUMMARY_SUCCESS",
    GET_ANNUAL_TARGET_SUMMARY_ERROR:"@@GET_ANNUAL_TARGET_SUMMARY_ERROR",
    GET_ANNUAL_TARGET_SUMMARY_RESET:"@@GET_ANNUAL_TARGET_SUMMARY_RESET",
};

export default GraphTypes;
