const ActiveEmployeeActionTypes = {

    // start list employee 
    GET_EMPLOYEE_LIST: '@@GET_EMPLOYEE_LIST',
    EMPLOYEE_LIST_LOADING: '@@EMPLOYEE_LIST/LOADING',
    EMPLOYEE_LIST_SUCESS: '@@EMPLOYEE_LIST/SUCESS',
    EMPLOYEE_LIST_ERROR: '@@EMPLOYEE_LIST/ERROR',

    // start create employee 
    CREATE_EMPLOYEE: '@@CREATE_EMPLOYEE',
    EMPLOYEE_CREATE_LOADING: '@@EMPLOYEE_CREATE/LOADING',
    EMPLOYEE_CREATE_SUCESS: '@@EMPLOYEE_CREATE/SUCESS',
    EMPLOYEE_CREATE_RESET: '@@EMPLOYEE_CREATE/RESET',
    EMPLOYEE_CREATE_ERROR: '@@EMPLOYEE_CREATE/ERROR',

    // start update employee 
    UPDATE_EMPLOYEE: '@@UPDATE_EMPLOYEE',
    EMPLOYEE_UPDATE_LOADING: '@@EMPLOYEE_UPDATE/LOADING',
    EMPLOYEE_UPDATE_SUCESS: '@@EMPLOYEE_UPDATE/SUCESS',
    EMPLOYEE_UPDATE_RESET: '@@EMPLOYEE_UPDATE/RESET',
    EMPLOYEE_UPDATE_ERROR: '@@EMPLOYEE_UPDATE/ERROR',
     // Reporting manager
     GET_REPORTING_MANAGER_BY_DESIGNATION: '@@GET_REPORTING_MANAGER_BY_DESIGNATION',
     GET_REPORTING_MANAGER_BY_DESIGNATION_LOADING: '@@GET_REPORTING_MANAGER_BY_DESIGNATION/LOADING',
     GET_REPORTING_MANAGER_BY_DESIGNATION_SUCESS: '@@GET_REPORTING_MANAGER_BY_DESIGNATION/SUCESS',
     GET_REPORTING_MANAGER_BY_DESIGNATION_RESET: '@@GET_REPORTING_MANAGER_BY_DESIGNATION/RESET',
     GET_REPORTING_MANAGER_BY_DESIGNATION_ERROR: '@@GET_REPORTING_MANAGER_BY_DESIGNATION/ERROR',


}
export default ActiveEmployeeActionTypes;