const Admin = {
    // start create employee 
    CREATE_COMPANY: '@@CREATE_COMPANY',
    COMPANY_CREATE_LOADING: '@@COMPANY_CREATE/LOADING',
    COMPANY_CREATE_SUCESS: '@@COMPANY_CREATE/SUCESS',
    COMPANY_CREATE_RESET: '@@COMPANY_CREATE/RESET',
    COMPANY_CREATE_ERROR: '@@COMPANY_CREATE/ERROR',

    COMPANY_LIST: '@@COMPANY_LIST',
    COMPANY_LIST_LOADING: '@@COMPANY_LIST/LOADING',
    COMPANY_LIST_SUCESS: '@@COMPANY_LIST/SUCESS',
    COMPANY_LIST_RESET: '@@COMPANY_LIST/RESET',
    COMPANY_LIST_ERROR: '@@COMPANY_LIST/ERROR',

    COMPANY_STATUS: '@@COMPANY_STATUS',
    COMPANY_STATUS_LOADING: '@@COMPANY_STATUS/LOADING',
    COMPANY_STATUS_SUCESS: '@@COMPANY_STATUS/SUCESS',
    COMPANY_STATUS_RESET: '@@COMPANY_STATUS/RESET',
    COMPANY_STATUS_ERROR: '@@COMPANY_STATUS/ERROR',

}
export default Admin;