const uploadTypes = {
    UPLOAD_TELLY :"@@UPLOAD_TELLY",
    UPLOAD_TELLY_LOADING : "@@UPLOAD_TELLY_LOADING",
    UPLOAD_TELLY_SUCCESS : "@@UPLOAD_TELLY_SUCCESS",
    UPLOAD_TELLY_RESET : "@@UPLOAD_TELLY_RESET",
    UPLOAD_TELLY_ERROR : "@@UPLOAD_TELLY_ERROR",


    UPLOAD_SECOND_FILE :"@@UPLOAD_SECOND_FILE",
    UPLOAD_SECOND_FILE_LOADING : "@@UPLOAD_SECOND_FILE_LOADING",
    UPLOAD_SECOND_FILE_SUCCESS : "@@UPLOAD_SECOND_FILE_SUCCESS",
    UPLOAD_SECOND_FILE_RESET : "@@UPLOAD_SECOND_FILE_RESET",
    UPLOAD_SECOND_FILE_ERROR : "@@UPLOAD_SECOND_FILE_ERROR",




    UPLOAD_SALARY_FILE : "@@UPLOAD_SALARY_FILE",
    UPLOAD_SALARY_FILE_LOADING : "@@UPLOAD_SALARY_FILE_LOADING",
    UPLOAD_SALARY_FILE_SUCCESS : "@@UPLOAD_SALARY_FILE_SUCCESS",
    UPLOAD_SALARY_FILE_RESET : "@@UPLOAD_SALARY_FILE_RESET",
    UPLOAD_SALARY_FILE_ERROR : "@@UPLOAD_SALARY_FILE_ERROR",


    

    UPLOAD_RATE_DIFFERENCE_FILE : "@@UPLOAD_RATE_DIFFERENCE_FILE",
    UPLOAD_RATE_DIFFERENCE_FILE_LOADING : "@@UPLOAD_RATE_DIFFERENCE_FILE_LOADING",
    UPLOAD_RATE_DIFFERENCE_FILE_SUCCESS : "@@UPLOAD_RATE_DIFFERENCE_FILE_SUCCESS",
    UPLOAD_RATE_DIFFERENCE_FILE_RESET : "@@UPLOAD_RATE_DIFFERENCE_FILE_RESET",
    UPLOAD_RATE_DIFFERENCE_FILE_ERROR : "@@UPLOAD_RATE_DIFFERENCE_FILE_ERROR",

}
export default uploadTypes