const TotalMonthSaleActionTypes = {

    // get month sale
    GET_TOTALMONTH_SALE: '@@GET_TOTALMONTH_SALE',
    TOTALMONTH_SALE_LOADING: '@@TOTALMONTH_SALE/LOADING',
    TOTALMONTH_SALE_SUCESS: '@@TOTALMONTH_SALE/SUCESS',
    TOTALMONTH_SALE_ERROR: '@@TOTALMONTH_SALE/ERROR',
    // get total expenditure

    GET_TOTAL_EXPENDITURE: '@@GET_TOTAL_EXPENDITURE',
    TOTAL_EXPENDITURE_LOADING: '@@TOTAL_EXPENDITURE/LOADING',
    TOTAL_EXPENDITURE_SUCESS: '@@TOTAL_EXPENDITURE/SUCESS',
    TOTAL_EXPENDITURE_ERROR: '@@TOTAL_EXPENDITURE/ERROR',
      // get MONTH expenditure

      GET_MONTH_EXPENDITURE: '@@GET_MONTH_EXPENDITURE',
      MONTH_EXPENDITURE_LOADING: '@@MONTH_EXPENDITURE/LOADING',
      MONTH_EXPENDITURE_SUCESS: '@@MONTH_EXPENDITURE/SUCESS',
      MONTH_EXPENDITURE_ERROR: '@@MONTH_EXPENDITURE/ERROR',
        // Get target achieved

        GET_TARGET_ACHIEVED: '@@GET_TARGET_ACHIEVED',
       TARGET_ACHIEVED_LOADING: '@@TARGET_ACHIEVED/LOADING',
       TARGET_ACHIEVED_SUCESS: '@@TARGET_ACHIEVED/SUCESS',
       TARGET_ACHIEVED_ERROR: '@@TARGET_ACHIEVED/ERROR',

      //  Get product wise report
     
      GET_PRODUCT_WISE_REPORT: '@@ GET_PRODUCT_WISE_REPORT',
     PRODUCT_WISE_REPORT_LOADING: '@@ PRODUCT_WISE_REPORT/LOADING',
     PRODUCT_WISE_REPORT_SUCESS: '@@PRODUCT_WISE_REPORT/SUCESS',
     PRODUCT_WISE_REPORT_ERROR: '@@PRODUCT_WISE_REPORT/ERROR',



     GET_PRODUCT_WISE_CSV_REPORT: '@@ GET_PRODUCT_WISE_CSV_REPORT',
     PRODUCT_WISE_REPORT_CSV_LOADING: '@@ PRODUCT_WISE_CSV_REPORT/LOADING',
     PRODUCT_WISE_REPORT_CSV_SUCESS: '@@PRODUCT_WISE_CSV_REPORT/SUCESS',
     PRODUCT_WISE_REPORT_CSV_RESET: '@@PRODUCT_WISE_CSV_REPORT/RESET',
     PRODUCT_WISE_REPORT_CSV_ERROR: '@@PRODUCT_WISE_CSV_REPORT/ERROR',

    //  Get annual sale graph
     
    GET_ANNUAL_SALE_GRAPH: '@@ GET_ANNUAL_SALE_GRAPH',
     GET_ANNUAL_SALE_GRAPH_LOADING: '@@ GET_ANNUAL_SALE_GRAPH/LOADING',
     GET_ANNUAL_SALE_GRAPH_SUCESS: '@@GET_ANNUAL_SALE_GRAPH/SUCESS',
     GET_ANNUAL_SALE_GRAPH_ERROR: '@@GET_ANNUAL_SALE_GRAPH/ERROR',


    //  Get OverAll wise Api 

    GET_OVERALL_DATA:"@@ GET_OVERALL_DATA",
    GET_OVERALL_DATA_LOADING:"GET_OVERALL_DATA_LOADING",
    GET_OVERALL_DATA_SUCCESS:"GET_OVERALL_DATA_SUCCESS",
    GET_OVERALL_DATA_ERROR:"GET_OVERALL_DATA_ERROR",
        //  Get Sale executive report Api 

        GET_SALE_EXECUTIVE_REPORT:"@@ GET_SALE_EXECUTIVE_REPORT",
        GET_SALE_EXECUTIVE_REPORT_LOADING:"GET_SALE_EXECUTIVE_REPORT_LOADING",
        GET_SALE_EXECUTIVE_REPORT_SUCCESS:"GET_SALE_EXECUTIVE_REPORT_SUCCESS",
        GET_SALE_EXECUTIVE_REPORT_ERROR:"GET_SALE_EXECUTIVE_REPORT_ERROR",

             //  Get Revenue by location

             GET_REVENUE_BY_LOCATION:"@@ GET_REVENUE_BY_LOCATION",
            GET_REVENUE_BY_LOCATION_LOADING:"GET_REVENUE_BY_LOCATION_LOADING",
            GET_REVENUE_BY_LOCATION_SUCCESS:"GET_REVENUE_BY_LOCATION_SUCCESS",
            GET_REVENUE_BY_LOCATION_ERROR:"GET_REVENUE_BY_LOCATION_ERROR",

              //  Get north zone report

              GET_NORTH_ZONE_REPORT:"@@ GET_NORTH_ZONE_REPORT",
              GET_NORTH_ZONE_REPORT_LOADING:"GET_NORTH_ZONE_REPORT_LOADING",
              GET_NORTH_ZONE_REPORT_SUCCESS:"GET_NORTH_ZONE_REPORT_SUCCESS",
              GET_NORTH_ZONE_REPORT_ERROR:"GET_NORTH_ZONE_REPORT_ERROR",

               //  Get South zone report

               GET_SOUTH_ZONE_REPORT:"@@ GET_SOUTH_ZONE_REPORT",
               GET_SOUTH_ZONE_REPORT_LOADING:"GET_SOUTH_ZONE_REPORT_LOADING",
               GET_SOUTH_ZONE_REPORT_SUCCESS:"GET_SOUTH_ZONE_REPORT_SUCCESS",
               GET_SOUTH_ZONE_REPORT_ERROR:"GET_SOUTH_ZONE_REPORT_ERROR",
               //  Get EAST zone report

               GET_EAST_ZONE_REPORT:"@@ GET_EAST_ZONE_REPORT",
               GET_EAST_ZONE_REPORT_LOADING:"GET_EAST_ZONE_REPORT_LOADING",
               GET_EAST_ZONE_REPORT_SUCCESS:"GET_EAST_ZONE_REPORT_SUCCESS",
               GET_EAST_ZONE_REPORT_ERROR:"GET_EAST_ZONE_REPORT_ERROR",
               //  Get WEST zone report

               GET_WEST_ZONE_REPORT:"@@ GET_WEST_ZONE_REPORT",
               GET_WEST_ZONE_REPORT_LOADING:"GET_WEST_ZONE_REPORT_LOADING",
               GET_WEST_ZONE_REPORT_SUCCESS:"GET_WEST_ZONE_REPORT_SUCCESS",
               GET_WEST_ZONE_REPORT_ERROR:"GET_WEST_ZONE_REPORT_ERROR",
               //  Get CENTRAL zone report

               GET_CENTRAL_ZONE_REPORT:"@@ GET_CENTRAL_ZONE_REPORT",
               GET_CENTRAL_ZONE_REPORT_LOADING:"GET_CENTRAL_ZONE_REPORT_LOADING",
               GET_CENTRAL_ZONE_REPORT_SUCCESS:"GET_CENTRAL_ZONE_REPORT_SUCCESS",
               GET_CENTRAL_ZONE_REPORT_ERROR:"GET_CENTRAL_ZONE_REPORT_ERROR",
                //  Get Bde list

                GET_BDE_LIST:"@@ GET_BDE_LIST",
                GET_BDE_LIST_LOADING:"@@GET_BDE_LIST_LOADING",
                GET_BDE_LIST_SUCCESS:"@@GET_BDE_LIST_SUCCESS",
                GET_BDE_LIST_RESET:"@@GET_BDE_LIST_RESET",
                GET_BDE_LIST_ERROR:"@@GET_BDE_LIST_ERROR",
                //  Get Bde South list

                GET_BDE_SOUTH_LIST:"@@ GET_BDE_SOUTH_LIST",
                GET_BDE_SOUTH_LIST_LOADING:"@@GET_BDE_SOUTH_LIST_LOADING",
                GET_BDE_SOUTH_LIST_SUCCESS:"@@GET_BDE_SOUTH_LIST_SUCCESS",
                GET_BDE_SOUTH_LIST_RESET:"@@GET_BDE_SOUTH_LIST_RESET",
                GET_BDE_SOUTH_LIST_ERROR:"@@GET_BDE_SOUTH_LIST_ERROR",
                //  Get Bde East list

                GET_BDE_EAST_LIST:"@@ GET_BDE_EAST_LIST",
                GET_BDE_EAST_LIST_LOADING:"@@GET_BDE_EAST_LIST_LOADING",
                GET_BDE_EAST_LIST_SUCCESS:"@@GET_BDE_EAST_LIST_SUCCESS",
                GET_BDE_EAST_LIST_RESET:"@@GET_BDE_EAST_LIST_RESET",
                GET_BDE_EAST_LIST_ERROR:"@@GET_BDE_EAST_LIST_ERROR",
                //  Get Bde WEST list

                GET_BDE_WEST_LIST:"@@ GET_BDE_WEST_LIST",
                GET_BDE_WEST_LIST_LOADING:"@@GET_BDE_WEST_LIST_LOADING",
                GET_BDE_WEST_LIST_SUCCESS:"@@GET_BDE_WEST_LIST_SUCCESS",
                GET_BDE_WEST_LIST_RESET:"@@GET_BDE_WEST_LIST_RESET",
                GET_BDE_WEST_LIST_ERROR:"@@GET_BDE_WEST_LIST_ERROR",
                 //  Get Bde CENTERAL list

                 GET_BDE_CENTER_LIST:"@@ GET_BDE_CENTER_LIST",
                 GET_BDE_CENTER_LIST_LOADING:"@@GET_BDE_CENTER_LIST_LOADING",
                 GET_BDE_CENTER_LIST_SUCCESS:"@@GET_BDE_CENTER_LIST_SUCCESS",
                 GET_BDE_CENTER_LIST_RESET:"@@GET_BDE_CENTER_LIST_RESET",
                 GET_BDE_CENTER_LIST_ERROR:"@@GET_BDE_CENTER_LIST_ERROR",

              //  GET filter product Data 
              GET_FILTER_PRODUCT_DATA:"@@ GET_FILTER_PRODUCT_DATA",
              GET_FILTER_PRODUCT_DATA_LOADING:"GET_FILTER_PRODUCT_DATA_LOADING",
              GET_FILTER_PRODUCT_DATA_SUCCESS:"GET_FILTER_PRODUCT_DATA_SUCCESS",
              GET_FILTER_PRODUCT_DATA_RESET:"GET_FILTER_PRODUCT_DATA_RESET",
              GET_FILTER_PRODUCT_DATA_ERROR:"GET_FILTER_PRODUCT_DATA_ERROR",
              // get vendor report
              GET_VENDOR_REPORT_DATA:"@@ GET_VENDOR_REPORT_DATA",
              GET_VENDOR_REPORT_DATA_LOADING:"@@GET_VENDOR_REPORT_DATA_LOADING",
              GET_VENDOR_REPORT_DATA_SUCCESS:"@@GET_VENDOR_REPORT_DATA_SUCCESS",
              GET_VENDOR_REPORT_DATA_RESET:"@@GET_VENDOR_REPORT_DATA_RESET",
              GET_VENDOR_REPORT_DATA_ERROR:"@@GET_VENDOR_REPORT_DATA_ERROR",


              GET_VENDOR_REPORT_CSV_REPORT: '@@ VENDOR_REPORT_CSV_REPORT',
      GET_VENDOR_REPORT_CSV_LOADING: '@@  VENDOR_REPORT_CSV_REPORT/LOADING',
      GET_VENDOR_REPORT_CSV_SUCESS: '@@ VENDOR_REPORT_CSV_REPORT/SUCESS',
      GET_VENDOR_REPORT_CSV_RESET: '@@ VENDOR_REPORT_CSV_REPORT/RESET',
      GET_VENDOR_REPORT_CSV_ERROR: '@@ VENDOR_REPORT_CSV_REPORT/ERROR',

                // get Product Detailreport
                GET_PRODUCT_DETAIL_REPORT:"@@ GET_PRODUCT_DETAIL_REPORT",
                GET_PRODUCT_DETAIL_REPORT_LOADING:"@@GET_PRODUCT_DETAIL_REPORT_LOADING",
                GET_PRODUCT_DETAIL_REPORT_SUCCESS:"@@GET_PRODUCT_DETAIL_REPORT_SUCCESS",
                GET_PRODUCT_DETAIL_REPORT_RESET:"@@GET_PRODUCT_DETAIL_REPORT_RESET",
                GET_PRODUCT_DETAIL_REPORT_ERROR:"@@GET_PRODUCT_DETAIL_REPORT_ERROR",

                 // get Vendor Detailreport
                 GET_VENDOR_DETAIL_REPORT:"@@ GET_VENDOR_DETAIL_REPORT",
                 GET_VENDOR_DETAIL_REPORT_LOADING:"@@GET_VENDOR_DETAIL_REPORT_LOADING",
                 GET_VENDOR_DETAIL_REPORT_SUCCESS:"@@GET_VENDOR_DETAIL_REPORT_SUCCESS",
                 GET_VENDOR_DETAIL_REPORT_RESET:"@@GET_VENDOR_DETAIL_REPORT_RESET",
                 GET_VENDOR_DETAIL_REPORT_ERROR:"@@GET_VENDOR_DETAIL_REPORT_ERROR",
}
export default TotalMonthSaleActionTypes;